name: run-pre-commit

on:
  - pull_request
  - push

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
      - name: Check if .gitignore contents were pushed
        run: test \! "$(git ls-files -i -c --exclude-from=.gitignore)"
